//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatPrisma.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatPrisma.Resources.Strings.de", typeof(Strings_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Text akzeptieren und in die Zwischenablage kopieren.
        ///STRG+Enter.
        /// </summary>
        public static string AcceptTextTooltip {
            get {
                return ResourceManager.GetString("AcceptTextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte tragen Sie einen OpenAI API-Key in den Einstellungen ein..
        /// </summary>
        public static string ApiKeyMissing {
            get {
                return ResourceManager.GetString("ApiKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto. einfügen.
        /// </summary>
        public static string AutoInsert {
            get {
                return ResourceManager.GetString("AutoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn angehakt, wird der Text automatisch in der vorherigen Anwendung eingefügt..
        /// </summary>
        public static string AutoInsertTooltip {
            get {
                return ResourceManager.GetString("AutoInsertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach Updates suchen.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit-ID:.
        /// </summary>
        public static string CommitID {
            get {
                return ResourceManager.GetString("CommitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte tragen Sie ein OpenAI Model in den Einstellungen ein..
        /// </summary>
        public static string ModelMissing {
            get {
                return ResourceManager.GetString("ModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Version: .
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Update verfügbar.
        /// </summary>
        public static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie verwenden im Moment die aktuellste Version von {0}!.
        /// </summary>
        public static string NoUpdateAvailableDescription {
            get {
                return ResourceManager.GetString("NoUpdateAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI.
        /// </summary>
        public static string OpenAI {
            get {
                return ResourceManager.GetString("OpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-Key.
        /// </summary>
        public static string OpenAIApiKey {
            get {
                return ResourceManager.GetString("OpenAIApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string OpenAIModel {
            get {
                return ResourceManager.GetString("OpenAIModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welches Model von OpenAI für die Textverbesserung verwendet werden soll.
        ///
        ///Zum Beispiel:
        ///• gpt-3.5-turbo
        ///• gpt-4
        ///• gpt-4-1106-preview.
        /// </summary>
        public static string OpenAIModelTooltip {
            get {
                return ResourceManager.GetString("OpenAIModelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-Source.
        /// </summary>
        public static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-Source Bibliotheken.
        /// </summary>
        public static string OpenSourceLibraries {
            get {
                return ResourceManager.GetString("OpenSourceLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wäre ohne die Unterstützung dieser Open-Source-Bibliotheken nicht möglich gewesen.
        ///
        ///Daher möchte ich mich herzlich bei allen Entwicklern dieser Bibliotheken bedanken..
        /// </summary>
        public static string OpenSourcePraise {
            get {
                return ResourceManager.GetString("OpenSourcePraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} automatisch mit Windows starten.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Version des aktuell angezeigten Textes.
        ///
        ///Vorherige Version:
        ///ALT+Links
        ///
        ///Nächste Version:
        ///ALT+Rechts.
        /// </summary>
        public static string StepperTooltip {
            get {
                return ResourceManager.GetString("StepperTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen.
        /// </summary>
        public static string TextEnhancement {
            get {
                return ResourceManager.GetString("TextEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anweisung wie der Text verbessert werden soll.
        /// </summary>
        public static string TextEnhancementPlaceholder {
            get {
                return ResourceManager.GetString("TextEnhancementPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update verfügbar.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Update für {0} steht zur Verfügung! .
        /// </summary>
        public static string UpdateAvailableDescription {
            get {
                return ResourceManager.GetString("UpdateAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt updaten!.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Version: .
        /// </summary>
        public static string YourVersion {
            get {
                return ResourceManager.GetString("YourVersion", resourceCulture);
            }
        }
    }
}
