//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatPrisma.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatPrisma.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the text and copy it into the clipboard.
        ///CTRL+Enter.
        /// </summary>
        public static string AcceptTextTooltip {
            get {
                return ResourceManager.GetString("AcceptTextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an OpenAI API key in the settings..
        /// </summary>
        public static string ApiKeyMissing {
            get {
                return ResourceManager.GetString("ApiKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto. insert.
        /// </summary>
        public static string AutoInsert {
            get {
                return ResourceManager.GetString("AutoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the text will be automatically inserted into the previous application..
        /// </summary>
        public static string AutoInsertTooltip {
            get {
                return ResourceManager.GetString("AutoInsertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit-ID:.
        /// </summary>
        public static string CommitID {
            get {
                return ResourceManager.GetString("CommitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an OpenAI model in the settings..
        /// </summary>
        public static string ModelMissing {
            get {
                return ResourceManager.GetString("ModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version: .
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        public static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently using the latest version of {0}!.
        /// </summary>
        public static string NoUpdateAvailableDescription {
            get {
                return ResourceManager.GetString("NoUpdateAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI.
        /// </summary>
        public static string OpenAI {
            get {
                return ResourceManager.GetString("OpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key.
        /// </summary>
        public static string OpenAIApiKey {
            get {
                return ResourceManager.GetString("OpenAIApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string OpenAIModel {
            get {
                return ResourceManager.GetString("OpenAIModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which OpenAI model should be used for text enhancements.
        ///
        ///Zum Beispiel:
        ///• gpt-3.5-turbo
        ///• gpt-4
        ///• gpt-4-1106-preview.
        /// </summary>
        public static string OpenAIModelTooltip {
            get {
                return ResourceManager.GetString("OpenAIModelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-source.
        /// </summary>
        public static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-source libraries.
        /// </summary>
        public static string OpenSourceLibraries {
            get {
                return ResourceManager.GetString("OpenSourceLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} would not have been possible without these open-source libraries.
        ///
        ///That&apos;s why I wanna say a big thank you to all developers of these libraries..
        /// </summary>
        public static string OpenSourcePraise {
            get {
                return ResourceManager.GetString("OpenSourcePraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start {0} automatically with Windows.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the currently shown text.
        ///
        ///Previous version:
        ///ALT+Left
        ///
        ///Next version:
        ///ALT+Right.
        /// </summary>
        public static string StepperTooltip {
            get {
                return ResourceManager.GetString("StepperTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string TextEnhancement {
            get {
                return ResourceManager.GetString("TextEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions how the text should be improved.
        /// </summary>
        public static string TextEnhancementPlaceholder {
            get {
                return ResourceManager.GetString("TextEnhancementPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for {0} is available!.
        /// </summary>
        public static string UpdateAvailableDescription {
            get {
                return ResourceManager.GetString("UpdateAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now!.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version: .
        /// </summary>
        public static string YourVersion {
            get {
                return ResourceManager.GetString("YourVersion", resourceCulture);
            }
        }
    }
}
